var GAME_LEVELS = [
  ["                                                                                ",
   "                                                 xxx                            ",
   "                                                xx!xx                           ",
   "                                                x!!!x                           ",
   "                                                xx!xx                           ",
   "                                                 xvx                            ",
   "                                   xxx                          xxx             ",
   "                                  xx!xx                        xx!xx            ",
   "                                  x!!!x                        x!!!x         x  ",
   "                                    !                          xx!xx         x  ",
   "                                    v                           xvx          x  ",
   "                                                                             x  ",
   "  x                                                                          x  ",
   "  x                     o                                                    x  ",
   "  x                                         o               o              o x  ",
   "  x                     o                               o                    x  ",
   "  x % @                                            ^ %  xx  x    o o       o x  ",
   "  xxxxxxxxxx    xxxxxxxxxxxxx   xxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "           x    x           x   x           x  x                                ",
   "           x    x           x   x           x  x                                ",
   "           x    x           x   x           x**x                                ",
   "           xxxxxx           *****                                               ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                        v       v    v                                                                            ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                            o                                                                     ",
   "                                           ooo                                                                    ",
   "                              %xxxo     xxxxxxxx                                                                  ",
   "                              x   x                                                                               ",
   "                            ox     x                                                                              ",
   "                            x       xxx                 o                                                         ",
   "                           x           xxxxxxxxxxxxx    x                                  o                      ",
   "                        ^ x                         x   x                                o  o                     ",
   "                       xxx                          x   x                      xxxxxxxxxxxxxx                     ",
   "                      x                             x   x    x                x                                   ",
   "                     x                              x   x      x             x                                    ",
   "                    x                               x   x        x         ox                                     ",
   "     @%            x                                x   x          x       x                                      ",
   "    xxx      xxxxxx                                 x   x            x   x                                        ",
   "    x x      x                                      x   x              !!                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x!!!x !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                 xxx                                                          ",
   "                                                xx!xx                                                         ",
   "                                                x!!!x                                                         ",
   "                                                xx!xx                           							  ",
   "                                                 xvx                                                          ",
   "  x                                                                                                         x ",
   "  x                                                                                          x  x           x ",
   "  x                                                                                         x               x ",
   "  x                                o                                                       x        x       x ",
   "  x                               xx                                                      x                 x ",
   "  x                             x     x                                     ^            x             x    x ",
   "  x         o                 x         xxxxxx              o             xxxx          x                o  x ",
   "  x     %@   xxx     o   ^   x                  xxxx        xxx       xxxx      xx      x                   x ",
   "  x     xx      xx  x  x xx                           xxxx       xxxx              % x                      x ",
   "  x !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  x ",                          
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
